# Generated by Django 4.1.5 on 2024-03-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoTexto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_Plus",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Plus"
                    ),
                ),
                (
                    "identificador",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Identificador do Documento",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
